version: '3'
services:
 backend-node:
  image: node
  container_name: backend-node
  build:
   context: reto_base_ldamian-nodejs
  networks:
   - net
 reverse-proxy-nginx:
  image: nginx
  container_name: reverse-proxy-nginx
  ports:
   - "80:80"
  build:
   context: reto_base_ldamian-nginx
  networks:
   - net
 pg:
  image: postgres
  container_name: reto_base_ldamian-postgres
  ports:
   - "5432:5432"
  environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testsuma
  volumes:
   - ./retobase-postgres/db_data:/var/lib/postgresql/data
  networks:
   - net
networks:
 net:
